---
- name: My test playbook
  hosts: all
  become: true
  tasks:
   - name: install pkg
     yum:
       name: httpd
       state: installed
     notify: start service

  handlers:
   - name: start service
     service:
       name: httpd
       state: started
