---
- name: My test playbook
  hosts: all
  become: true
  tasks:
   - name: stop pkg
     service:
       name: httpd
       state: stopped

   - name: uninstall service
     yum:
       name: httpd
       state: removed
